DB_SCHEMA: main
server:
  port: 8080
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.imdbsecondedition: DEBUG
spring:
  #Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/imdbsecondedition?currentSchema=${DB_SCHEMA}
    username: postgres
    password: e0VdC~0wO@JHfHZ$CS56RbY1o|DtKfTqpiiRL~O#vCKaCdwfX207}
  #Migrations
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5432/imdbsecondedition?currentSchema=${DB_SCHEMA}
    user: postgres
    password: e0VdC~0wO@JHfHZ$CS56RbY1o|DtKfTqpiiRL~O#vCKaCdwfX207}
    change-log: db/changelog/changelog-master.yaml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
